### ISSUE TITLE
Pimcore 11 set config locations

### ISSUE THREAD

**Issue by valentin-** [BlackbitDigitalCommerce/pimcore-single-sign-on#7]
Hi, I've installed Versions 1.1.9 with Pimcore 11.1.3 but I'm not able to save the config using the settings-store.

As explained in the readme.md I've added this line to the .env file but has no effect:
`PIMCORE_WRITE_TARGET_SSO: settings-store`

I think the content for the yaml file unter Configuration storage (readme) is invalid, trying to set the config as used for other components won't work:

```
blackbit_single_sign_on:
    config_location:
        single-sign-on:
            write_target:
                type: 'settings-store'
            read_target:
                type: 'settings-store'
```

Unrecognized option "single_sign_on" under "blackbit_single_sign_on.config_location". Did you mean "single-sign-on"? 
Probably a typo with -/_ in the config reader?

Or did I miss something?

Thanks,
Valentin

**Comment by BlackbitDevs** [comment]
Hi @valentin-,

what does `bin/console config:dump-reference blackbit_single_sign_on` provide you?

Should be something like
```
blackbit_single_sign_on:
  config_location:
        single-sign-on:
            write_target:
                type:                 symfony-config # One of "symfony-config"; "settings-store"; "disabled"
                options:

                    # Default:
                    directory:           /var/www/html/var/config/single-sign-on
```

**Comment by valentin-** [comment]
Hi @BlackbitDevs, yes I'm getting the same output and it's already defined like that. But getting the error.

```
blackbit_single_sign_on:
    config_location:
        single-sign-on:
            write_target:
                type: settings-store
```

![image](https://github.com/BlackbitDigitalCommerce/pimcore-single-sign-on/assets/90033/80abdc1c-bc0f-44da-9a6f-e17a3b4c73e9)

**Comment by BlackbitDevs** [comment]
Is fixed in 1.1.13.

Please change config to
```yaml
blackbit_single_sign_on:
  config_location:
    write_target:
      type: 'settings-store'
```
